### PR TITLE
Omega / kodi 21 enabled

### PR DESCRIPTION
**Pull request by alexbelgium**
Enables kodi 21 support

Tested working

### CODE REVIEW

**Comment by magico1010** [comment]
Hello,
Favourites not working.
Have anybody a solution ?

**Comment by alexbelgium** [comment]
Ah sorry I don't use this feature and have really 0 idea how the skin works I just applied the change for it to run on omega :)

**Comment by codi71** [comment]
try this, I modified it, it works for me https://www.dropbox.com/scl/fi/k41jhjxigdqbylelliuj4/skin.auramod-1.1.9.0.21.zip?rlkey=mvjeb1fndvfg5j62gdzli3xqr&st=svixu17b&dl=0

**Comment by magico1010** [comment]
> Versuchen Sie dies, ich habe es geändert, es funktioniert bei mir https://www.dropbox.com/scl/fi/k41jhjxigdqbylelliuj4/skin.auramod-1.1.9.0.21.zip?rlkey=mvjeb1fndvfg5j62gdzli3xqr&st=svixu17b&dl=0

Thank you codi71, it works .

**Comment by alexbelgium** [comment]
Updated to v2.0.0

**Comment by alexbelgium** [comment]
Updated to v2.0.1

**Comment by alexbelgium** [comment]
Update to 2.0.2 align to nexus as base

**Comment by alexbelgium** [comment]
Replaced by official release for omega! Thanks to the maintainer!

**Pull request closed without merging**
