### PR TITLE
Change & to &amp; and add missing variable in Includes_Labels/Topbar.xml

### PR DESCRIPTION
**Pull request by jojobrogess**
I just went through the 1080i folder inside SBT3 with the kodidevkit addon. It can detect possible faults. 
If any of this is wrong, let me know.

### CODE REVIEW

**Comment by inb4after** [comment]
After all localization commits are done I will squash them and then merge this one. Just in case we have to easily revert, as we don't know what this will do (but all seems good in review, just needs testing)

**Comment by jojobrogess** [comment]
I also noticed there looks to be a missing `)` in Includes_Object.xml line 967 
https://github.com/SerpentDrago/skin.auramod/blob/3a7e8efab2944b98ee0b41a134e8c624acc5a3a5/1080i/Includes_Object.xml#L967
Doesn't through a syntax error though, seems to be a mild suggestion? idk what im doing tbh lol 
and I don't know how this operates well enough to know where exactly to place the `)`


How I noticed it(everything's purple, all 8.1k lines after that point):
************************************************************************************************************************************
2021-06-18 20_55_37-Greenshot
************************************************************************************************************************************


First solution:
`Control.HasFocus(30222) | ControlGroup(505).HasFocus)`<- closing it off at the end(column 227), just before the `]` and `</autoscroll>`
************************************************************************************************************************************
2021-06-18 20_55_47-Greenshot
************************************************************************************************************************************



Second solution:
`(Window(Home).Property(trailer_trailerwillplaying))`<- double it up there(column 98), just before the ` + [Control.HasFocus(300) | `
************************************************************************************************************************************
2021-06-18 20_56_03-Greenshot

************************************************************************************************************************************


Both close the expression, but placement obviously matters.

**Comment by inb4after** [comment]
It's `String.IsEmpty(Window(Home).Property(trailer_trailerwillplaying))` (second solution), to close the `String.IsEmpty()`.

**Comment by jojobrogess** [comment]
Now that localization has been completed and merged, I'll close this for now and redo it later on tonight. 

As well as the playlist pull request I've been sitting on

**Pull request closed without merging**
