### PR TITLE
Translation to Portuguese from Brazil.

### PR DESCRIPTION
**Pull request by Havokdan**
Translation to Portuguese from Brazil.
I do not know if I did the correct way, I do not know how the right github works ...

### CODE REVIEW

**Comment by SerpentDrago** [comment]
you somehow managed to make a file called "language/resource.language.pt_br\strings.po" Instead of making a file called strings.po inside a folder called resource.language.pt_br
You need to modify the file/folder structure on your Patch-1 branch , and then this pr will be accepted . 
https://github.com/Havokdan/skin.auramod/tree/patch-1

no need to make a new pr , any changes you make on that branch on your github will be reflected in this pr . let me know when done  .

**Comment by inb4after** [comment]
This also needs to be targeted at Localization branch instead of the Matrix branch, please open new PR after completing the above changes.

**Comment by Havokdan** [comment]
I ended up doing new PR, I still could not make change in the structure of PR. 
Edit.: Now I managed to make the change (I think). Now I will try to delete new PR

**Comment by SerpentDrago** [comment]
It's much easier to use git / github though a local client and manipulating files locally. Then push changes to remote. instead of doing everything though website. Just FYI in future.

Looks good!

**Pull request merged**
