### PR TITLE
Update Spanish New

### PR DESCRIPTION
**Pull request by gtkingbuild**
I have expanded the Spanish translation of Auramod
I have all the files in the 1080i folder updated from the latest version of Auramod that you have uploaded to github (version v1.0.35)
They are all translated with the $ LOCALIZE tags
And I have the strings.po file expanded for all translations

### CODE REVIEW

**Comment by inb4after** [comment]
Thanks for PR. Some changes needed before merge.

---

1\. What was the reasoning behind changes to `1080i/Custom_1116_ColorBoxAdvancedSettings.xml`: https://github.com/SerpentDrago/skin.auramod/pull/131/files#diff-a91585ab0cf367f875c1e87ab1829df389679cd3132bdadc4333819883d1c276

---

2\. Lines like this `1080i/Custom_1126_MovieHub_config.xml`: https://github.com/SerpentDrago/skin.auramod/pull/131/files#diff-d2ec747f1751677fedc3d9c8cef3fa6c80984bad4c66aa16cc49eaf50faa41e1L17

Format with `[CAPITALIZE]` and `[/CAPITALIZE]` (and other tags like `[B]`,`[/B]`) should be kept in the skin and not transferred to strings.po, so after changes it should look like `<label>[CAPITALIZE]$LOCALIZE[31585][/CAPITALIZE]</label>`.

---

3\. Lines like this `1080i/Custom_1126_MovieHub_config.xml`: https://github.com/SerpentDrago/skin.auramod/pull/131/files#diff-d2ec747f1751677fedc3d9c8cef3fa6c80984bad4c66aa16cc49eaf50faa41e1L64

Format with spaces and `-` should be kept in the skin and not transferred to strings.po, so after changes it should look like:
`<label> - $LOCALIZE[31588]</label>`

---

4\. We need to add comments `<!-- label text here -->` so we can easily know what the LOCALIZE code is in English when working on the skin and can be searched easily. For example `1080i/Custom_1136_Search.xml`: https://github.com/SerpentDrago/skin.auramod/pull/131/files#diff-557b053bc5dbb83e828fbc6f17e2998be26732cfb21c3397cdeda3b8000dd637L31

This will become `<label>$LOCALIZE[31720]</label> <!-- Search for TV Shows and Movies -->`

---

5\. Mistake in diff `Expand 1080i/DialogVideoInfo-Includes.xml`: https://github.com/SerpentDrago/skin.auramod/pull/131/files#diff-7ede3fe4cf8db4ac958a52ae83d57b5077c60016b53283f5c0d7408e8a982891L1472

---

6\. Some unnecessary changes: 

- `Expand 1080i/SkinSettings.xml`: https://github.com/SerpentDrago/skin.auramod/pull/131/files#diff-fe35ee495bc7d5e1993aee6230c9a3c36402b93fb0c4ada0cecac3ab906e83bbR163

- `Expand 1080i/SkinSettings.xml`: https://github.com/SerpentDrago/skin.auramod/pull/131/files#diff-fe35ee495bc7d5e1993aee6230c9a3c36402b93fb0c4ada0cecac3ab906e83bbR1719

---

7\. These changes need separate PR `Expand 1080i/SkinSettings.xml`: https://github.com/SerpentDrago/skin.auramod/pull/131/files#diff-fe35ee495bc7d5e1993aee6230c9a3c36402b93fb0c4ada0cecac3ab906e83bbR1722

---

8\. We need to add default strings.po `language/resource.language.en_gb/strings.po`

---

**Comment by gtkingbuild** [comment]
Thanks to you for following the Auramod project for Matrix.

Regarding point one, I had to resize the window as the translated text was coming out of it and mixed with one of the buttons.

With the rest of the changes you ask me, I have everything more or less clear, except for point number 8, since SerpentDrago told me that the lines added to the strings.po Spanish file should also be added to the strings.po of resource.language.en_us

The other points I will do as you indicate, the only thing that will cost me a while since I am doing them little by little.

**Comment by inb4after** [comment]
> 
> 
> Thanks to you for following the Auramod project for Matrix.
> 
> Regarding point one, I had to resize the window as the translated text was coming out of it and mixed with one of the buttons.
> 
> With the rest of the changes you ask me, I have everything more or less clear, except for point number 8, since SerpentDrago told me that the lines added to the strings.po Spanish file should also be added to the strings.po of resource.language.en_us
> 
> The other points I will do as you indicate, the only thing that will cost me a while since I am doing them little by little.

I'm working on fixing some issues with current localization files, and then I will add `en_gb` so you don't have to do anything. But I recommend that you wait until these changes are made before making your own changes, to prevent conflict issues, as I will be adding some new strings.

**Comment by inb4after** [comment]
> 
> 
> Thanks to you for following the Auramod project for Matrix.
> 
> Regarding point one, I had to resize the window as the translated text was coming out of it and mixed with one of the buttons.
> 
> With the rest of the changes you ask me, I have everything more or less clear, except for point number 8, since SerpentDrago told me that the lines added to the strings.po Spanish file should also be added to the strings.po of resource.language.en_us
> 
> The other points I will do as you indicate, the only thing that will cost me a while since I am doing them little by little.

I'm in the process of merging your changes and adding the above changes, you don't need to do anything else. Thanks for working on this!

**Comment by inb4after** [comment]
Unfortunately there is a mistake in `Expand en_us strings.po`: 

https://github.com/SerpentDrago/skin.auramod/pull/131/files#diff-17103c7452727e4fdd2bc115bd8028b7abeca01d97cb4081b542d74183dc8f66R3108

https://github.com/SerpentDrago/skin.auramod/pull/131/files#diff-17103c7452727e4fdd2bc115bd8028b7abeca01d97cb4081b542d74183dc8f66R3113

`31642` appears twice, which means all id's after this are wrong.

**Comment by inb4after** [comment]
I've changed my mind on `<!-- -->` comments so the code looks a little cleaner, sorry about that.

**Comment by gtkingbuild** [comment]
Sorry mate, I didn't see your recommendation about waiting for me as you are adding new strings.  I have advanced the work and have already fixed several files.  I have gone in order until I get to the include_objects.xml file.
At the moment I am staying there for today.  I think tomorrow I'll be done with everything you asked me to do, so ... Could it be possible that you could wait until tomorrow to add the strings you have in mind?

**Comment by inb4after** [comment]
Thanks for the fixes, I can wait before reviewing, just let me know when you're finished.

> 
> 
> Sorry mate, I didn't see your recommendation about waiting for me as you are adding new strings. I have advanced the work and have already fixed several files. I have gone in order until I get to the include_objects.xml file.
> At the moment I am staying there for today. I think tomorrow I'll be done with everything you asked me to do, so ... Could it be possible that you could wait until tomorrow to add the strings you have in mind?

**Comment by inb4after** [comment]
> 
> 
> Sorry mate, I didn't see your recommendation about waiting for me as you are adding new strings. I have advanced the work and have already fixed several files. I have gone in order until I get to the include_objects.xml file.
> At the moment I am staying there for today. I think tomorrow I'll be done with everything you asked me to do, so ... Could it be possible that you could wait until tomorrow to add the strings you have in mind?

Thanks for the fixes, I can wait before reviewing further, just let me know when you're finished.

**Comment by gtkingbuild** [comment]
Thank you

> > Sorry mate, I didn't see your recommendation about waiting for me as you are adding new strings. I have advanced the work and have already fixed several files. I have gone in order until I get to the include_objects.xml file.
> > At the moment I am staying there for today. I think tomorrow I'll be done with everything you asked me to do, so ... Could it be possible that you could wait until tomorrow to add the strings you have in mind?
> 
> Thanks for the fixes, I can wait before reviewing further, just let me know when you're finished.

Thank you Man....
So I remove <! --.... ->?

**Comment by inb4after** [comment]
> 
> 
> Thank you
> 
> > > Sorry mate, I didn't see your recommendation about waiting for me as you are adding new strings. I have advanced the work and have already fixed several files. I have gone in order until I get to the include_objects.xml file.
> > > At the moment I am staying there for today. I think tomorrow I'll be done with everything you asked me to do, so ... Could it be possible that you could wait until tomorrow to add the strings you have in mind?
> > 
> > 
> > Thanks for the fixes, I can wait before reviewing further, just let me know when you're finished.
> 
> Thank you Man....
> So I remove <! --.... ->?

Since they're already added, we should leave them in there. I thought it would be too much work to add everything back, but it looks fine from my side. Thanks again.

**Comment by gtkingbuild** [comment]
> > Thank you
> > > > Sorry mate, I didn't see your recommendation about waiting for me as you are adding new strings. I have advanced the work and have already fixed several files. I have gone in order until I get to the include_objects.xml file.
> > > > At the moment I am staying there for today. I think tomorrow I'll be done with everything you asked me to do, so ... Could it be possible that you could wait until tomorrow to add the strings you have in mind?
> > > 
> > > 
> > > Thanks for the fixes, I can wait before reviewing further, just let me know when you're finished.
> > 
> > 
> > Thank you Man....
> > So I remove <! --.... ->?
> 
> Since they're already added, we should leave them in there. I thought it would be too much work to add everything back, but it looks fine from my side. Thanks again.

Good morning partner,

I think all the changes you asked me have made are already done. Observe them and tell me if everything is correct, or if on the contrary there is something else to change.

Regards my friend.

**Comment by inb4after** [comment]
Thanks, I'll let you know if anything comes up in review!

**Pull request merged**
