### PR TITLE
General Playlist fix with some new additions.

### PR DESCRIPTION
**Pull request by jojobrogess**
Pretty general clean up/update.
I tried to get everything working correctly. 

Let me know if I didn't do something right or added too many "fixes" lol

### CODE REVIEW

**Comment by inb4after** [comment]
Thanks for the PR, I'll review it soon.

**Comment by inb4after** [comment]
The strange naming of the original playlists makes deciphering which playlists to change/add difficult, but overall these changes are in the right direction. Here is a quick cheat sheet for the consolidated changes we're looking for:

---

- In-progress Episodes
- In-progress TV Shows
- In-progress Movies

Rule: `inprogress` `true`
Order: `lastplayed` Descending

---

New... > Recently added...
- Recently Added Episodes
- Recently Added TV Shows
- Recently Added Movies

Order: `dateadded` Descending

---

- Recently Aired Episodes - Rule: `airdate` `inthelast` `14 days` - Order: `airdate` Descending
- Recently Aired TV Shows - Rule: `premiered` `inthelast` `14 days` - Order: `premiered` Descending
- Recently Released Movies - Rule: `premiered` `inthelast` `14 days` - Order: `premiered` Descending

---

- Recently Watched Episodes
- Recently Watched TV Shows
- Recently Watched Movies

Rule: `lastplayed` `inthelast` `28 days`
Rule: `playcount` `greaterthan` `0`
Rule: `inprogress` `false`
Order: `lastplayed` Descending

---

- Watched Episodes
- Watched TV Shows
- Watched Movies

Rule: `playcount` `greaterthan` `0`
Order: `lastplayed` Descending

---

- Unwatched Episodes - Order: `tvshowtitle` Descending
- Unwatched TV Shows - Order: `random` Descending
- Unwatched Movies - Order: `random` Descending

Rule: `playcount` `is` `0`
Rule: `inprogress` `false`

---

Random... and TopRated... smart playlists can be left as originals.

Let me know your thoughts on this.

**Comment by jojobrogess** [comment]
Thank you for the list, I'll go through and make all of these adjustments and report back.

**Comment by inb4after** [comment]
> 
> 
> Thank you for the list, I'll go through and make all of these adjustments and report back.

Thanks, also please make your changes on a new clean branch from latest Matrix branch.

**Comment by jojobrogess** [comment]
Looks like these don't work:

***********************************************************************************************************************************
- Recently Aired Episodes - Rule: airdate inthelast 14 days - Order: airdate Descending

- Recently Aired TV Shows - Rule: premiered inthelast 14 days - Order: premiered Descending

- Recently Released Movies - Rule: premiered inthelast 14 days - Order: premiered Descending
***********************************************************************************************************************************

Ordering by premiered is not possible, you can only order by `Year` 
and
Using `first aired` in the last 14 days isn't working for Movies/TVShows.
It's just displaying all titles in year order.

**Comment by inb4after** [comment]
Episode "AirDate" grouping should be working according to wiki.

For TV Shows and Movies you can change all "premiered" to "Year".

**Pull request closed without merging**
