### PR TITLE
Startup Video - revise handling of startup video

### PR DESCRIPTION
**Pull request by Fatal-Errol**
This fixes the problem that I have with using the startup video. 

> Right after the startup video plays, the screen goes black until I press the back button as if there is a black page blocking the home screen. On my android 9 tv, this is consistent no matter what video I add. It's not consistent in windows 10.

The fix is the same as what jurialmunkey did when I opened the issue in arctic.horizon.

https://github.com/jurialmunkey/skin.arctic.horizon/commit/eb6012ba7bf68fd8bc23e3836ce45a08f1e561bc

I ported that in this PR and it fixed the issue that I have. Basically this revises how the startup video is played and removes the need for Custom_1113_AutoPlaylist.xml.

### CODE REVIEW

**Comment by inb4after** [comment]
Thanks for the contribution. The issue is that the video can no longer be exited early when back is pressed, the only way to do this would be to have the loop. This feature also needs to be implemented in the loop as it isn't working in any branch.

**Comment by inb4after** [comment]
I've made a new [commit](https://github.com/SerpentDrago/skin.auramod/commit/4d77acd52305938d7b40de926833e0890bf0250b) which should fix this issue.

You can test the fix by installing the [Testing branch](https://github.com/SerpentDrago/skin.auramod/tree/Testing) which includes this fix and others.

It allows both exiting the startup video early using back/backspace, and exiting the startup video properly when it is finished.

Please test and report any further bugs, as I used a workaround to reproduce this bug.

**Comment by SerpentDrago** [comment]
@Fatal-Errol  please test , Testing branch when you get a chance , thanks :) 

also Any and all fix's prs / slight tweaks to design we are open to . I notice your kinda working on your own little fork . If theres any changes you would like to see in Auramod perm.  , you can open a issue and discus it . If it means more eyes / people working on this the better.

**Comment by Fatal-Errol** [comment]
Hi @inb4after,

Sorry just saw your comment. Confirmed that your update also fixed my issue so I'll be closing this now. Thanks!

**Comment by Fatal-Errol** [comment]
@SerpentDrago yes I'm just playing around right now and learning by modifying files. Once I'm confident that a change will not affect other features then I'll send a pr.

**Pull request closed without merging**
