### PR TITLE
Fixed widgetAspect for skin shortcuts

### LINKED ISSUE #6: [Bug] Search Results are not in the default veiw when you hover over them.
**Describe the bug**
I don't really think this is a bug but when i search for something, Every poster that i hover to goes to landscape view and i looked in the skin settings but i could not find the fix for it.

**To Reproduce**
1. Go to settings and go to Search list.
2. In Search list find an addon that you would like to add to your search.
3. Try searching something in the search bar and get result
4. Hover over the posters and see the error that they are in landscape view. 

**Expected behavior**
See the search results in poster view.

**Screenshots** 
Veiw

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version Kodi 19 Matrix

**Additional context**
I don't know why they are in landscape view but i hope this is an error or bug and hope this can be fixed in the future.

### PR DESCRIPTION
**Pull request by inb4after**
This fixes #6

### CODE REVIEW

**Comment by Goldenfreddy0703** [comment]
Hey i reviewed your fix but i think the search results are still in landscape view sadly. Is there anything i have to do in this fix?

**Comment by Dealz-416LS** [comment]
> Hey i reviewed your fix but i think the search results are still in landscape view sadly. Is there anything i have to do in this fix?

<s>For regular Widgets</s>
<s>You have re-do the widget, The fix won't fix the existing widget so the widget needs to be re-done.</s>
<s>Go to where you edit the widget then select the widget `Choose Widget` or `Action` to re-do the widget.</s>

Better solution provided by @inb4after in comment below.

**Comment by inb4after** [comment]
@Goldenfreddy0703 Forgot to mention this yeah. Follow @Dealz-416LS and force skinshortcuts to rebuild the menu. Instead of pointing the widget somewhere else, you could: change the aspect to poster then back to landscape, or enable spotlight then disable it again, in order to force the menu to rebuild.

You should only need to do this for one widget and it should fix all of them. 

Please report back with your results.

**Comment by Goldenfreddy0703** [comment]
Ok thank you, I will try that soon and see if it fixes it.

**Comment by Dealz-416LS** [comment]
> 
> 
> Ok thank you, I will try that soon and see if it fixes it.

It should, Everything is good at my end.

Widgets for Search list, Hubs and My Lists are all good!

**Pull request merged**
